# Generated by Django 4.0.4 on 2022-05-26 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbot',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bot_Data',
        ),
        migrations.DeleteModel(
            name='Tbot',
        ),
    ]
