# Generated by Django 4.0.4 on 2022-05-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t_bot', '0003_alter_bot_data_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbot', to=settings.AUTH_USER_MODEL),
        ),
    ]
