# Generated by Django 4.0.4 on 2022-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
