# Generated by Django 4.0.4 on 2022-05-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_assets', '0002_alter_asset_name_alter_asset_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name', 'ticker', 'logo']},
        ),
        migrations.AddField(
            model_name='asset',
            name='logo',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
